[package]
name = "ray-tracer"
version = "0.1.0"
authors = ["jjant <jantonielli@itba.edu.ar>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[lib]
name = "ray_tracer"
path = "../src/lib.rs"
